# Generated by Django 5.1.2 on 2024-11-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
