# Generated by Django 5.1.2 on 2024-11-08 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('relase_date', models.DateField()),
                ('rating', models.IntegerField()),
                ('muscian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician_info.musician')),
            ],
        ),
    ]
