# Generated by Django 5.1.2 on 2024-11-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='relase_date',
            new_name='release_date',
        ),
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.IntegerField(choices=[(1, '1-Poor'), (2, '2-Not Good'), (3, '3-Good'), (4, '4-Very Good'), (5, '5-Excellent')]),
        ),
    ]
