# Generated by Django 5.1.2 on 2024-11-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album_info', '0002_rename_relase_date_album_release_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='muscian',
            new_name='musician',
        ),
    ]
